<a href="https://colab.research.google.com/github/deepak2407/COVID2019-Analysis/blob/master/corona.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
#data from John Hopkins University
!git clone https://github.com/CSSEGISandData/COVID-19.git
# !wget https://github.com/CSSEGISandData/COVID-19/blob/master/time_series/time_series_2019-ncov-Confirmed.csv
# !wget https://github.com/CSSEGISandData/COVID-19/blob/master/time_series/time_series_2019-ncov-Deaths.csv
# !wget https://github.com/CSSEGISandData/COVID-19/blob/master/time_series/time_series_2019-ncov-Recovered.csv

Cloning into 'COVID-19'...
remote: Enumerating objects: 243, done.
remote: Counting objects: 100% (243/243), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 12494 (delta 111), reused 195 (delta 64), pack-reused 12251
Receiving objects: 100% (12494/12494), 40.46 MiB | 42.71 MiB/s, done.
Resolving deltas: 100% (5971/5971), done.

In [15]:
%cd COVID-19/
!ls

/content/COVID-19/csse_covid_19_data/csse_covid_19_time_series/COVID-19
archived_data  csse_covid_19_data  README.md  who_covid_19_situation_reports

In [16]:
%cd /content/COVID-19/csse_covid_19_data/csse_covid_19_time_series
!ls

/content/COVID-19/csse_covid_19_data/csse_covid_19_time_series
COVID-19			    time_series_19-covid-Deaths.csv
README.md			    time_series_19-covid-Recovered.csv
time_series_19-covid-Confirmed.csv

In [17]:
import pandas as pd
conf_df=pd.read_csv("time_series_19-covid-Confirmed.csv")
# death_df=pd.read_csv(death_csv_url)
# recov_df=pd.read_csv(recov_csv_url)
conf_df.head()
# death_df.head()
# recov_df.head()

  Province/State  Country/Region      Lat  ...  3/8/20  3/9/20  3/10/20
0          Anhui  Mainland China  31.8257  ...     990     990      990
1        Beijing  Mainland China  40.1824  ...     428     428      429
2      Chongqing  Mainland China  30.0572  ...     576     576      576
3         Fujian  Mainland China  26.0789  ...     296     296      296
4          Gansu  Mainland China  36.0611  ...     124     124      125

[5 rows x 53 columns]

In [0]:
conf_df_latest=pd.DataFrame()
for i in range(len(conf_df.columns.values)):
  if(i<=3):
   conf_df_latest[conf_df.columns[i]]=conf_df[conf_df.columns[i]]
#getting the latest date details of confirmed cases
latest_date_conf=conf_df.columns.values[-1]
conf_df_latest[latest_date_conf]=conf_df[latest_date_conf]

In [21]:
conf_df_latest.head()

  Province/State  Country/Region      Lat      Long  3/10/20
0          Anhui  Mainland China  31.8257  117.2264      990
1        Beijing  Mainland China  40.1824  116.4142      429
2      Chongqing  Mainland China  30.0572  107.8740      576
3         Fujian  Mainland China  26.0789  117.9874      296
4          Gansu  Mainland China  36.0611  103.8343      125